name: Test Runner

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  test:
    runs-on: self-hosted  # This specifies the job will run on the self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run some task
        run: echo "GitHub Actions runner is running on Kubernetes!"
