name: Actions Runner Controller Demo
on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: gha-runner-scale-set-1742984217
    steps:
    - run: echo "🎉 This job uses runner scale set runners dind!" && sleep 1000
